pragma solidity ^0.8.0;

import "./ERC721PresetMinterPauserAutoIdURIStorage.sol";

contract ERC721PresetMinterPauserAutoIdURIStorageMintable is ERC721PresetMinterPauserAutoIdURIStorage {

    /**
     * @dev Function to mint tokens.
     * @param to The address that will receive the minted tokens.
     * @param tokenId The token id to mint.
     * @param tokenURI The token URI of the minted token.
     * @return A boolean that indicates if the operation was successful.
     */
    function mintWithTokenURI(address to, string memory tokenURI) public onlyMinter returns (bool) {
        uint256 tokenId = super.mint(to);
        _setTokenURI(tokenId, tokenURI);
        return true;
    }


    /**
 * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    constructor(
        string memory name,
        string memory symbol
    ) ERC721PresetMinterPauserAutoId(name, symbol) {

    }

}
